name: Build

on:
  workflow_dispatch:

jobs:
  build:
    env:
      ELECTRON_BUILDER_PUBLISH: never
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            script: build:mac:arm64
            artifact: qury-mac
            artifactPath: dist/release/qury-mac.zip
          - os: windows-latest
            script: build:win:x64
            artifact: qury-windows
            artifactPath: dist/release/qury-windows.zip
          - os: ubuntu-latest
            script: build:linux:deb
            artifact: qury-linux
            artifactPath: dist/release/qury-linux.deb
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run ${{ matrix.script }}
        env:
          ELECTRON_BUILDER_PUBLISH: never

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifactPath }}
          retention-days: 3
